Override transitive dependency
Override transitive dependency on spring-core and spring-context 5.2.x,
as otherwise we geta NoClassDefFoundError for ConcurrentLruCache which
was introduced in spring-core 5.3.0

#75